### ISSUE TITLE
Has anyone tried to build native micronaut with cassandra feature?

### ISSUE THREAD

**Issue by ilkin** [micronaut-projects/micronaut-cassandra#41]
Has anyone tried to build native micronaut with cassandra feature? Please help. When I build simple micronaut cassandra application with graalvm below exception thrown:

`
applicationType: default
defaultPackage: com.example
testFramework: junit
sourceLanguage: java
buildTool: gradle
features: [app-name, cassandra, docker, file-watch, graalvm, gradle, http-client, java, java-application, junit, logback, netty-server, readme, shade, yaml]
`

`native-image --no-server -cp build/libs/demo-0.1-all.jar`

`Fatal error: java.lang.NoClassDefFoundError: Lorg/apache/ivy/Ivy;
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
    at java.lang.Class.getDeclaredField(Class.java:2068)
    at com.oracle.graal.pointsto.infrastructure.OriginalFieldProvider.getJavaField(OriginalFieldProvider.java:43)
    at com.oracle.graal.pointsto.meta.AnalysisField.getJavaField(AnalysisField.java:420)
    at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readUninitializedStaticValue(AnalysisConstantReflectionProvider.java:136)
    at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:87)
    at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:77)
    at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:175)
    at com.oracle.graal.pointsto.ObjectScanner$1.run(ObjectScanner.java:103)
    at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.apache.ivy.Ivy
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
    ... 16 more`

**Comment by ilopmar** [comment]
@ilkin I don't have experience with Cassandra. If you create a simple application that uses it I can give it a try to make it work with GraalVM.

**Comment by knoma** [comment]
There seems the be still an issue - I tried to create a Cassandra native app with Micronaut `2.5.0` and `2.5.1 ` plus `graalvm-ce-java11  21.1.0 (graalvm64-11.0.11)` / `graalvm-ce-java8   21.0.0.2 `and the native app throws and error at start. 

I tried to build the native image via   `./gradlew clean nativeImage` and `native-image` but no luck.

Here is a [demo to test this](https://github.com/knoma/cassnative) 

I was able to build the same business logic with quarkus, Cassandra  and `graalvm-ce-java11   21.1.0 (graalvm64-11.0.11)`
[see code](https://github.com/knoma/cass-quarkus) 

I'm not sure if this a GraalVM or Cass driver issue.

Can some please look into this? Maybe it make sense to add this as a test similar to the [JDBC  test](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.0.x_h2)

It would be pleasure to submit this test id wished.


thank you

**Comment by knoma** [comment]
@ilkin maybe you can give a try with micronaut 2.5.1 and  graalvm-ce-java11  21.1.0 

thank you

**Comment by ilopmar** [comment]
Fixed in #154 and released in Micronaut Cassandra 3.2.0
